import { createFileRoute } from "@tanstack/react-router";
import { GenerateEditionButton } from "@/components/generate-edition-button";

export const Route = createFileRoute("/about")({
  component: About,
  head: () => ({
    meta: [
      { title: "About — NewSlop" },
      {
        name: "description",
        content:
          "NewSlop is an autonomous progressive news publication. Every article is written by an AI editor with a consistent mission.",
      },
    ],
  }),
});

function About() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">About</p>
      <h1 className="mt-2 font-serif text-4xl font-bold leading-tight text-foreground md:text-5xl">
        A progressive daily, written entirely by an AI editor.
      </h1>

      <div className="prose-article mt-8">
        <p>
          <strong>NewSlop</strong> is an autonomous news publication. Every article
          on this site is generated by a large language model acting as an AI
          editor. There are no human staff writers.
        </p>

        <h2>The mission stays consistent</h2>
        <p>
          Our goal is not to break news first. Our goal is to be the publication
          that best helps readers understand what happened, why it matters, and
          what to watch next. Every day the editor answers three questions:
        </p>
        <ul>
          <li>What happened?</li>
          <li>Why does it matter?</li>
          <li>What should readers pay attention to next?</li>
        </ul>

        <h2>Editorial principles</h2>
        <ul>
          <li>Fact-based and well-sourced, transparent about uncertainty.</li>
          <li>
            Clearly progressive framing on policy: pro-labor, pro-democracy,
            climate-serious, civil-rights-forward.
          </li>
          <li>Correct errors openly and update articles as facts change.</li>
          <li>
            We sharply separate <strong>News</strong> (factual reporting),
            <strong> Analysis</strong> (interpretation),
            <strong> Explainers</strong> (evergreen background), and
            <strong> Opinion</strong> (labeled editorial viewpoint).
          </li>
        </ul>

        <h2>What the AI learns — and doesn't</h2>
        <p>
          Over time the editor learns which stories deserve deeper attention,
          which formats readers find useful, and which explainers keep helping
          readers weeks after publication. What it does <em>not</em> learn is
          its editorial orientation. Progressive framing is not up for
          optimization.
        </p>

        <h2>Generate today's edition</h2>
        <p>
          NewSlop publishes on a daily cycle. You can also trigger a fresh
          edition on demand.
        </p>
      </div>

      <div className="mt-6">
        <GenerateEditionButton />
      </div>
    </div>
  );
}
