import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/privacy")({
  component: Privacy,
  head: () => ({
    meta: [
      { title: "Privacy Policy — The Progressor" },
      {
        name: "description",
        content:
          "The Progressor's privacy policy explains what data we collect, how we use it, and your rights as a reader.",
      },
      { property: "og:title", content: "Privacy Policy — The Progressor" },
      {
        property: "og:description",
        content:
          "The Progressor's privacy policy explains what data we collect, how we use it, and your rights as a reader.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
});

function Privacy() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Legal</p>
      <h1 className="mt-2 font-serif text-4xl font-bold leading-tight text-foreground md:text-5xl">
        Privacy Policy
      </h1>
      <p className="mt-4 text-sm text-muted-foreground">
        Last updated: August 13, 2026
      </p>

      <div className="prose-article mt-8">
        <p>
          This Privacy Policy describes how The Progressor collects, uses, and
          protects information about visitors and registered readers of our
          publication.
        </p>

        <h2>1. What we collect</h2>
        <p>
          <strong>Account information.</strong> When you sign up with email and
          password or through Google OAuth, we store your email address, a
          unique user identifier, and basic profile information provided by the
          authentication service.
        </p>
        <p>
          <strong>Reader interactions.</strong> We collect the votes, saves,
          follows, keywords, and search queries you create while using the
          site. Public upvote counts are displayed alongside articles. Downvotes
          and other private signals are stored for your account only.
        </p>
        <p>
          <strong>Usage and device data.</strong> We collect standard server
          logs, page views, and device/browser information to understand how
          readers use the site and to diagnose problems.
        </p>
        <p>
          <strong>Crowdsource submissions.</strong> If you submit a story idea
          through our Crowdsource chat, we store the conversation, links you
          share, and any notes you provide.
        </p>

        <h2>2. How we use your data</h2>
        <ul>
          <li>To provide and maintain your account and dashboard.</li>
          <li>To personalize your reading experience, such as highlighting topics you follow.</li>
          <li>To display public upvote counts and aggregate reader interest signals.</li>
          <li>To improve our editorial coverage and site performance.</li>
          <li>To communicate important updates about the publication.</li>
          <li>To comply with legal obligations and protect the security of the site.</li>
        </ul>

        <h2>3. Cookies and analytics</h2>
        <p>
          We use cookies and similar technologies to keep you signed in, remember
          your preferences, and analyze traffic. Analytics data is aggregated and
          used to improve the publication. You can disable cookies in your browser,
          but some features may not work correctly.
        </p>

        <h2>4. Third-party services</h2>
        <p>
          We use trusted third-party providers for authentication, hosting,
          analytics, and news data (including NewsAPI). These providers have
          access only to the information necessary to perform their services and
          are contractually obligated to protect it.
        </p>

        <h2>5. AI-generated content</h2>
        <p>
          All articles on The Progressor are generated by AI. Reader interactions
          may be used in aggregate to inform editorial priorities, but we do
          not use individual account data to train third-party AI models.
        </p>

        <h2>6. Data retention</h2>
        <p>
          We keep your account and interaction data for as long as your account
          is active. You can request deletion of your account and associated data
          at any time by contacting us.
        </p>

        <h2>7. Your rights</h2>
        <p>
          Depending on where you live, you may have the right to access, correct,
          delete, or export your personal data, or to object to certain uses.
          Contact us to exercise these rights.
        </p>

        <h2>8. Children's privacy</h2>
        <p>
          The Progressor is intended for readers 18 and older. We do not
          knowingly collect personal information from children under 16. Some
          interactive features, such as Crowdsource submissions, require
          confirmation that you are 18 or older.
        </p>

        <h2>9. Contact us</h2>
        <p>
          If you have questions about this Privacy Policy or your data, please
          contact us at discussabilityonline@gmail.com.
        </p>
      </div>
    </div>
  );
}
