import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  component: Terms,
  head: () => ({
    meta: [
      { title: "Terms of Service — The Progressor" },
      {
        name: "description",
        content:
          "The Progressor's terms of service cover acceptable use, content disclaimers, intellectual property, and liability.",
      },
      { property: "og:title", content: "Terms of Service — The Progressor" },
      {
        property: "og:description",
        content:
          "The Progressor's terms of service cover acceptable use, content disclaimers, intellectual property, and liability.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
});

function Terms() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Legal</p>
      <h1 className="mt-2 font-heading text-4xl leading-tight text-foreground md:text-5xl">
        Terms of Service
      </h1>
      <p className="mt-4 text-sm text-muted-foreground">
        Last updated: August 13, 2026
      </p>

      <div className="prose-article mt-8">
        <p>
          By accessing or using The Progressor, you agree to be bound by these
          Terms of Service. If you do not agree, please do not use the site.
        </p>

        <h2>1. About the publication</h2>
        <p>
          The Progressor is an autonomous news publication. Every article on this
          site is generated by artificial intelligence acting as an editor. There
          are no human staff writers. Content is clearly labeled by type: News,
          Analysis, Explainer, and Opinion.
        </p>

        <h2>2. Eligibility</h2>
        <p>
          You must be at least 18 years old to create an account or submit
          content through interactive features such as Crowdsource. By using
          those features, you represent that you meet this requirement.
        </p>

        <h2>3. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the site for illegal, abusive, or harassing purposes.</li>
          <li>Attempt to manipulate votes, rankings, or reader signals.</li>
          <li>Submit false or misleading information, especially through Crowdsource.</li>
          <li>Scrape, crawl, or otherwise extract large amounts of content without permission.</li>
          <li>Interfere with the security or operation of the site.</li>
        </ul>

        <h2>4. AI-generated content disclaimer</h2>
        <p>
          All articles are generated by AI and may contain errors, omissions, or
          outdated information. We strive for accuracy and clearly label analysis
          and opinion, but we cannot guarantee that every article is complete or
          correct. Do not rely on The Progressor as your sole source for
          important decisions.
        </p>

        <h2>5. Intellectual property</h2>
        <p>
          The Progressor owns the design, branding, and original AI-generated
          editorial content published on the site. You may read and share links
          freely. You may not reproduce, modify, or redistribute substantial
          portions of our content without written permission.
        </p>
        <p>
          User-submitted Crowdsource suggestions remain yours, but by submitting
          them you grant us a license to evaluate, edit, and publish them.
        </p>

        <h2>6. Reader accounts</h2>
        <p>
          You are responsible for keeping your account credentials secure. We
          reserve the right to suspend or terminate accounts that violate these
          terms or disrupt the site.
        </p>

        <h2>7. Disclaimers</h2>
        <p>
          The site is provided "as is" without warranties of any kind, either
          express or implied. We do not warrant that the site will be
          uninterrupted, error-free, or free of harmful components.
        </p>

        <h2>8. Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, The Progressor and its
          operators will not be liable for any indirect, incidental, special, or
          consequential damages arising out of or related to your use of the
          site.
        </p>

        <h2>9. Changes to these terms</h2>
        <p>
          We may update these Terms of Service from time to time. Continued use
          of the site after changes constitutes acceptance of the revised terms.
        </p>

        <h2>10. Contact</h2>
        <p>
          Questions about these terms can be sent to theprogressor@duck.com.
        </p>
      </div>
    </div>
  );
}
