/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicTopicRouteImport } from './routes/topic.$topic'
import { Route as KindKindRouteImport } from './routes/kind.$kind'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ApiPublicHooksGenerateOpinionRouteImport } from './routes/api/public/hooks/generate-opinion'
import { Route as ApiPublicHooksGenerateExplainersRouteImport } from './routes/api/public/hooks/generate-explainers'
import { Route as ApiPublicHooksGenerateEditionRouteImport } from './routes/api/public/hooks/generate-edition'
import { Route as ApiPublicHooksGenerateAnalysisRouteImport } from './routes/api/public/hooks/generate-analysis'
import { Route as ApiPublicHooksBackfillTopicsRouteImport } from './routes/api/public/hooks/backfill-topics'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicTopicRoute = TopicTopicRouteImport.update({
  id: '/topic/$topic',
  path: '/topic/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const KindKindRoute = KindKindRouteImport.update({
  id: '/kind/$kind',
  path: '/kind/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGenerateOpinionRoute =
  ApiPublicHooksGenerateOpinionRouteImport.update({
    id: '/api/public/hooks/generate-opinion',
    path: '/api/public/hooks/generate-opinion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateExplainersRoute =
  ApiPublicHooksGenerateExplainersRouteImport.update({
    id: '/api/public/hooks/generate-explainers',
    path: '/api/public/hooks/generate-explainers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateEditionRoute =
  ApiPublicHooksGenerateEditionRouteImport.update({
    id: '/api/public/hooks/generate-edition',
    path: '/api/public/hooks/generate-edition',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateAnalysisRoute =
  ApiPublicHooksGenerateAnalysisRouteImport.update({
    id: '/api/public/hooks/generate-analysis',
    path: '/api/public/hooks/generate-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillTopicsRoute =
  ApiPublicHooksBackfillTopicsRouteImport.update({
    id: '/api/public/hooks/backfill-topics',
    path: '/api/public/hooks/backfill-topics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topics': typeof TopicsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/kind/$kind': typeof KindKindRoute
  '/topic/$topic': typeof TopicTopicRoute
  '/api/public/hooks/backfill-topics': typeof ApiPublicHooksBackfillTopicsRoute
  '/api/public/hooks/generate-analysis': typeof ApiPublicHooksGenerateAnalysisRoute
  '/api/public/hooks/generate-edition': typeof ApiPublicHooksGenerateEditionRoute
  '/api/public/hooks/generate-explainers': typeof ApiPublicHooksGenerateExplainersRoute
  '/api/public/hooks/generate-opinion': typeof ApiPublicHooksGenerateOpinionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topics': typeof TopicsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/kind/$kind': typeof KindKindRoute
  '/topic/$topic': typeof TopicTopicRoute
  '/api/public/hooks/backfill-topics': typeof ApiPublicHooksBackfillTopicsRoute
  '/api/public/hooks/generate-analysis': typeof ApiPublicHooksGenerateAnalysisRoute
  '/api/public/hooks/generate-edition': typeof ApiPublicHooksGenerateEditionRoute
  '/api/public/hooks/generate-explainers': typeof ApiPublicHooksGenerateExplainersRoute
  '/api/public/hooks/generate-opinion': typeof ApiPublicHooksGenerateOpinionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topics': typeof TopicsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/kind/$kind': typeof KindKindRoute
  '/topic/$topic': typeof TopicTopicRoute
  '/api/public/hooks/backfill-topics': typeof ApiPublicHooksBackfillTopicsRoute
  '/api/public/hooks/generate-analysis': typeof ApiPublicHooksGenerateAnalysisRoute
  '/api/public/hooks/generate-edition': typeof ApiPublicHooksGenerateEditionRoute
  '/api/public/hooks/generate-explainers': typeof ApiPublicHooksGenerateExplainersRoute
  '/api/public/hooks/generate-opinion': typeof ApiPublicHooksGenerateOpinionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/topics'
    | '/article/$slug'
    | '/kind/$kind'
    | '/topic/$topic'
    | '/api/public/hooks/backfill-topics'
    | '/api/public/hooks/generate-analysis'
    | '/api/public/hooks/generate-edition'
    | '/api/public/hooks/generate-explainers'
    | '/api/public/hooks/generate-opinion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/topics'
    | '/article/$slug'
    | '/kind/$kind'
    | '/topic/$topic'
    | '/api/public/hooks/backfill-topics'
    | '/api/public/hooks/generate-analysis'
    | '/api/public/hooks/generate-edition'
    | '/api/public/hooks/generate-explainers'
    | '/api/public/hooks/generate-opinion'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/topics'
    | '/article/$slug'
    | '/kind/$kind'
    | '/topic/$topic'
    | '/api/public/hooks/backfill-topics'
    | '/api/public/hooks/generate-analysis'
    | '/api/public/hooks/generate-edition'
    | '/api/public/hooks/generate-explainers'
    | '/api/public/hooks/generate-opinion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TopicsRoute: typeof TopicsRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  KindKindRoute: typeof KindKindRoute
  TopicTopicRoute: typeof TopicTopicRoute
  ApiPublicHooksBackfillTopicsRoute: typeof ApiPublicHooksBackfillTopicsRoute
  ApiPublicHooksGenerateAnalysisRoute: typeof ApiPublicHooksGenerateAnalysisRoute
  ApiPublicHooksGenerateEditionRoute: typeof ApiPublicHooksGenerateEditionRoute
  ApiPublicHooksGenerateExplainersRoute: typeof ApiPublicHooksGenerateExplainersRoute
  ApiPublicHooksGenerateOpinionRoute: typeof ApiPublicHooksGenerateOpinionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$topic': {
      id: '/topic/$topic'
      path: '/topic/$topic'
      fullPath: '/topic/$topic'
      preLoaderRoute: typeof TopicTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kind/$kind': {
      id: '/kind/$kind'
      path: '/kind/$kind'
      fullPath: '/kind/$kind'
      preLoaderRoute: typeof KindKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-opinion': {
      id: '/api/public/hooks/generate-opinion'
      path: '/api/public/hooks/generate-opinion'
      fullPath: '/api/public/hooks/generate-opinion'
      preLoaderRoute: typeof ApiPublicHooksGenerateOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-explainers': {
      id: '/api/public/hooks/generate-explainers'
      path: '/api/public/hooks/generate-explainers'
      fullPath: '/api/public/hooks/generate-explainers'
      preLoaderRoute: typeof ApiPublicHooksGenerateExplainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-edition': {
      id: '/api/public/hooks/generate-edition'
      path: '/api/public/hooks/generate-edition'
      fullPath: '/api/public/hooks/generate-edition'
      preLoaderRoute: typeof ApiPublicHooksGenerateEditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-analysis': {
      id: '/api/public/hooks/generate-analysis'
      path: '/api/public/hooks/generate-analysis'
      fullPath: '/api/public/hooks/generate-analysis'
      preLoaderRoute: typeof ApiPublicHooksGenerateAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-topics': {
      id: '/api/public/hooks/backfill-topics'
      path: '/api/public/hooks/backfill-topics'
      fullPath: '/api/public/hooks/backfill-topics'
      preLoaderRoute: typeof ApiPublicHooksBackfillTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TopicsRoute: TopicsRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  KindKindRoute: KindKindRoute,
  TopicTopicRoute: TopicTopicRoute,
  ApiPublicHooksBackfillTopicsRoute: ApiPublicHooksBackfillTopicsRoute,
  ApiPublicHooksGenerateAnalysisRoute: ApiPublicHooksGenerateAnalysisRoute,
  ApiPublicHooksGenerateEditionRoute: ApiPublicHooksGenerateEditionRoute,
  ApiPublicHooksGenerateExplainersRoute: ApiPublicHooksGenerateExplainersRoute,
  ApiPublicHooksGenerateOpinionRoute: ApiPublicHooksGenerateOpinionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
